dist: xenial  # required to run 3.7+
language: python
python: 3.7
install:
  - pip install django pytest pytest-cov codecov

script:
  - py.test  --cov-report term --cov=django_context_decorator

after_success:
  - codecov
